### PR TITLE
#6 prometheus reporter

### PR DESCRIPTION
**Pull request by Rurouni**
I have added prometheus reporter as asp.net core middleware.
To use one should add middleware as `appBuilder.UsePrometheus()` and then `/metrics` endpoint will be availiable to be scraped by Prometheus.
By default returns text protocol, to enable protobuf one can register `PrometheusMetricsMiddlewareOptions` with `UseProtobuf = true`

### CODE REVIEW

**Comment by alhardy** [comment]
@Rurouni cool, I really like the idea of using protobuf as prometheous has as an option.

A thought, rather than include the prometheous middleware as a reporting extension, how about move that as a formatter extension like [App.Metrics.Formatters.Json](https://github.com/alhardy/AppMetrics/tree/dev/src) re-using the same middleware in [App.Metrics.Extensions.Middleware](https://github.com/alhardy/AppMetrics/blob/dev/src/App.Metrics.Extensions.Middleware/MetricsEndpointMiddleware.cs), there is an `IMetricDataSerializer`

**Comment by Rurouni** [comment]
I was originally thinking about it but that approach was too limiting. 

- IMetricSerializer interface assumes that you you work with string and not raw bytes, and for proto you should return raw bytes and not strnig
- No ability to override content type
- also Deserialize method is questionable, majority of cases would not require it, only if you need some kind of intermediary through Kafka/EventHub with actual reporter only at the end. But even in that case I would use my own DTOs/serialiser infrastructure rather taking dependency on AppMetrics here.

I feel that it should be just IMetricsFormatter.Format: MetricSnapshot -> (contentType, byte[])

**Comment by alhardy** [comment]
OK, I'll do a bit of refactoring on that

**Comment by alhardy** [comment]
@Rurouni I've moved the existing json serializer classes into the `App.Metrics.Formatters.Json` project. 

`App.Metrics.Extensions.Middleware` now contains two abstractions `IMetricsResponseWriter` and `IHealthResponseWriter` (health probably doesn't need to be formatted any other way just added this for consistency really). With this you should be able to have a separate package `App.Metrics.Formatters.Prometheus` which includes all the protobuf models and serialization related stuff as  `App.Metrics.Formatters.Json` does.

See https://github.com/alhardy/AppMetrics/commit/36c461a30786cb45433db89382c17575875d50d7

So you should just be able to implement something like https://github.com/alhardy/AppMetrics/commit/36c461a30786cb45433db89382c17575875d50d7#diff-17b658ca6c7dcbea0248aea558f9105a for prometheus protobuf and your ASCII formatter. These could just be configurable as extension methods on `IMetricsHostBuilder` for example https://github.com/alhardy/AppMetrics/commit/36c461a30786cb45433db89382c17575875d50d7#diff-51ddb2edde50f9493d9fcb92d3a11281

```
AddPrometheusProtoSerialization(this IMetricsHostBuilder host)
AddPrometheusAsciiSerialization(this IMetricsHostBuilder host)
```

This will allow the same [`MetricsEndpointMiddleware`](https://github.com/alhardy/AppMetrics/commit/36c461a30786cb45433db89382c17575875d50d7#diff-a8da529ba9b6e4d422517d9022a2ede1) to be used.

What are your thoughts on keeping `App.Metrics.Formatters.Prometheus` as a separate repo on your github account? Otherwise I'm happy to create  a separate for this as I think It (as well as the elastic search and influxdb reporter) belong in their own repos.

**Comment by alhardy** [comment]
Moved to https://github.com/alhardy/AppMetrics.Extensions.Prometheus

**Pull request closed without merging**
